# Generated by Django 5.1 on 2024-11-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='convenio',
            field=models.CharField(default='Nenhum', max_length=14),
        ),
        migrations.AddField(
            model_name='exame',
            name='especialidade',
            field=models.CharField(default='Nenhuma', max_length=14),
        ),
        migrations.AddField(
            model_name='exame',
            name='horario',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='exame',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1),
        ),
    ]
