# Generated by Django 5.1 on 2024-11-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_exame_convenio_exame_especialidade_exame_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='convenio',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='Nenhum', max_length=14),
        ),
        migrations.AlterField(
            model_name='exame',
            name='especialidade',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='Nenhuma', max_length=14),
        ),
        migrations.AlterField(
            model_name='exame',
            name='horario',
            field=models.TimeField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='08:00'),
        ),
    ]
