# Generated by Django 5.1 on 2024-11-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_alter_exame_convenio_alter_exame_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='convenio',
            field=models.CharField(default='Nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='exame',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exame',
            name='especialidade',
            field=models.CharField(default='Nenhuma', max_length=50),
        ),
        migrations.AlterField(
            model_name='exame',
            name='horario',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='medico_preferencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exame',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exame',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
    ]
