# Generated by Django 5.1 on 2024-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_alter_paciente_data_nascimento_alter_paciente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(default='Especialidade', max_length=100),
        ),
    ]
