# Generated by Django 5.1 on 2024-11-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_alter_medico_data_nascimento_alter_medico_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('horario', models.TimeField(default='08:00')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadeClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExameAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('horario', models.TimeField(default='08:00')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExameClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.AddField(
            model_name='convenio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='cobertura',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='contato',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='validade',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='consultaagendada',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.convenio'),
        ),
        migrations.AddField(
            model_name='consultaagendada',
            name='medico_preferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medico'),
        ),
        migrations.AddField(
            model_name='consultaagendada',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente'),
        ),
        migrations.AddField(
            model_name='consultaagendada',
            name='consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidadeclinica'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidadeclinica'),
        ),
        migrations.AddField(
            model_name='exameagendado',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.convenio'),
        ),
        migrations.AddField(
            model_name='exameagendado',
            name='medico_preferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medico'),
        ),
        migrations.AddField(
            model_name='exameagendado',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente'),
        ),
        migrations.AddField(
            model_name='exameagendado',
            name='exame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.exameclinica'),
        ),
    ]
