# Generated by Django 5.1 on 2024-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_exameclinica_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidadeclinica',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exameclinica',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
